project:
  type: website
  output-dir: _site

website:
  title: "Robert Annabel"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
  page-footer:
    center: "Robert Annabel &nbsp;·&nbsp; School of Economics, University of Sydney"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
